version: "3"

services:

  db:
    container_name: mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      
      MYSQL_DATABASE: favorite_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INIT_COMMAND: "SET GLOBAL host_cache_size=0"

    working_dir: /var/lib/mysql
    volumes:
        - "./mysql:/var/lib/mysql:rw"
      
    ports:
      - "3306:3306"

  admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  api:
    container_name: api_favorite

    build: .
    restart: always
    ports:
      - "7070:6060"

    links:
      - db
    depends_on:
      - db

    env_file: 
      - .env

